name: jnotes
description: Simple notepad app in Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+4

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.2.6
  sqflite_common_ffi: ^2.2.2
  
  path_provider: ^2.0.14
  path: ^1.8.2
  fluttertoast: ^8.2.1
  share_plus: ^7.2.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  local_auth: ^2.2.0
  shared_preferences: ^2.3.2
  flutter_localizations: # Suporte para internacionalização no Flutter
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true